import Foundation
import Testing
@testable import MarqueeCore

@Suite("Appcast manifest")
struct AppcastManifestTests {
    // MARK: Validation

    @Test func aSchemaWeDoNotUnderstandIsRefused() {
        let appcast = Appcast(
            schema: 2,
            releases: [UpdatesManifest.release("0.1.30")])
        #expect(throws: UpdateError.unsupportedSchema(2)) { try appcast.validate() }
    }

    @Test func aManifestNamingAnotherAppIsRefused() {
        let appcast = Appcast(app: "com.example.someone-else", releases: [UpdatesManifest.release("0.1.30")])
        #expect(throws: UpdateError.foreignManifest("com.example.someone-else")) { try appcast.validate() }
    }

    @Test func ourOwnManifestValidates() throws {
        let appcast = UpdatesManifest.appcast(releases: [UpdatesManifest.release("0.1.30")])
        #expect(throws: Never.self) { try appcast.validate() }
        #expect(appcast.app == "com.danskullz.marquee")
        #expect(appcast.schema == 1)
    }

    @Test func schemaIsCheckedBeforeTheAppIdentifier() {
        let appcast = Appcast(schema: 9, app: "com.example.other", releases: [])
        #expect(throws: UpdateError.unsupportedSchema(9)) { try appcast.validate() }
    }

    // MARK: Decoding

    @Test func theManifestThePublisherWritesDecodesExactly() throws {
        let bytes = try Data(contentsOf: try #require(updatesFixture("appcast-0.1.30.json")))
        // Generated by scripts/make-appcast.sh, byte for byte.
        let appcast = try Appcast.decode(from: bytes)

        #expect(appcast.schema == 1)
        #expect(appcast.app == "com.danskullz.marquee")
        #expect(appcast.signatureURL?.absoluteString == "https://tv.guihot.net/appcast-0.1.30.sig")
        // `generatedAt` is written as `%Y-%m-%dT%H:%M:%SZ`; the decoder has to agree with that.
        #expect(appcast.generatedAt == Date(timeIntervalSince1970: 1_791_709_200))
        #expect(appcast.releases.map(\.version.description) == ["0.1.30", "0.1.29"])

        let newest = try #require(appcast.releases.first)
        #expect(newest.channel == .beta)
        #expect(!newest.yanked)
        #expect(newest.minimumVersion == nil)
        #expect(newest.publishedAt == Date(timeIntervalSince1970: 1_791_709_200))
        #expect(newest.notes?.contains("in-app updater") == true)
        #expect(newest.builds.map(\.arch) == [.arm64, .x86_64, .universal])
        #expect(newest.builds.allSatisfy { $0.minOS == "15.0" && $0.size > 0 && $0.sha256.count == 64 })
        #expect(newest.builds[0].url.absoluteString
            == "https://tv.guihot.net/downloads/Marquee-0.1.30-macos-arm64.zip")
    }

    @Test func thePublishedManifestStillValidatesAndOffersAnUpdate() throws {
        let appcast = try Appcast.decode(from: try Data(contentsOf: try #require(updatesFixture("appcast-0.1.30.json"))))
        try appcast.validate()
        let offered = try #require(appcast.update(from: UpdateVersion("0.1.28"), channel: .beta, host: .arm64))
        #expect(offered.version == UpdateVersion("0.1.30"))
        #expect(offered.build(for: .arm64)?.arch == .arm64)
        #expect(offered.build(for: .x86_64)?.arch == .x86_64)
    }

    @Test func aTimestampWithFractionalSecondsAlsoDecodes() throws {
        // Not what the publisher writes today, but a future `datetime.isoformat()` would, and a
        // decoder that rejected it would lock every install out of updating.
        let json = """
            {"schema":1,"app":"com.danskullz.marquee","generatedAt":"2026-10-11T09:00:00.123Z",\
            "releases":[{"version":"0.1.30","channel":"beta","publishedAt":"2026-10-11T09:00:00.000Z",\
            "yanked":false,"builds":[]}]}
            """
        let appcast = try Appcast.decode(from: Data(json.utf8))
        // Compared with a tolerance: `Date` equality is exact, and two ways of spelling the same
        // instant a fraction of a second apart are not bit-identical doubles.
        let generated = try #require(appcast.generatedAt)
        #expect(abs(generated.timeIntervalSince1970 - (1_791_709_200 + 0.123)) < 0.001)
        #expect(appcast.releases.first?.publishedAt == Date(timeIntervalSince1970: 1_791_709_200))
    }

    @Test func bytesThatAreNotAManifestAreRejected() {
        #expect(throws: (any Error).self) { try Appcast.decode(from: Data("<html>502</html>".utf8)) }
        #expect(throws: (any Error).self) { try Appcast.decode(from: Data()) }
    }

    // MARK: Selection

    @Test func theNewestReleaseOfferedToAClientThreeBuildsBehindIsTheNewest() throws {
        let appcast = UpdatesManifest.appcast(releases: [
            UpdatesManifest.release("0.1.28"),
            UpdatesManifest.release("0.1.30"),
            UpdatesManifest.release("0.1.29"),
        ])
        let offered = try #require(appcast.update(from: UpdateVersion("0.1.28"), channel: .beta, host: .arm64))
        #expect(offered.version == UpdateVersion("0.1.30"))
        // And the ordering is the reason: 0.1.30 outranks 0.1.9 numerically.
        #expect(appcast.sortedReleases.map(\.version.description) == ["0.1.30", "0.1.29", "0.1.28"])
    }

    @Test func aClientAlreadyOnTheNewestIsOfferedNothing() {
        let appcast = UpdatesManifest.appcast(releases: [
            UpdatesManifest.release("0.1.30"),
            UpdatesManifest.release("0.1.29"),
        ])
        #expect(appcast.update(from: UpdateVersion("0.1.30"), channel: .beta, host: .arm64) == nil)
        #expect(appcast.update(from: UpdateVersion("0.1.31"), channel: .beta, host: .arm64) == nil)
    }

    @Test func aYankedReleaseIsInvisible() throws {
        let appcast = UpdatesManifest.appcast(releases: [
            UpdatesManifest.release("0.1.30", yanked: true),
            UpdatesManifest.release("0.1.29"),
        ])
        // Withdrawn, but still downloadable for anyone already mid-download.
        #expect(appcast.sortedReleases.map(\.version.description) == ["0.1.30", "0.1.29"])
        let offered = try #require(appcast.update(from: UpdateVersion("0.1.28"), channel: .beta, host: .arm64))
        #expect(offered.version == UpdateVersion("0.1.29"))
    }

    @Test func everyReleaseYankedOffersNothing() {
        let appcast = UpdatesManifest.appcast(releases: [
            UpdatesManifest.release("0.1.30", yanked: true),
            UpdatesManifest.release("0.1.29", yanked: true),
        ])
        #expect(appcast.update(from: UpdateVersion("0.1.1"), channel: .beta, host: .arm64) == nil)
    }

    @Test func minimumVersionExcludesAClientTooOldToJumpStraightThere() throws {
        let appcast = UpdatesManifest.appcast(releases: [
            UpdatesManifest.release("0.1.30", minimumVersion: "0.1.20"),
            UpdatesManifest.release("0.1.29"),
        ])
        #expect(appcast.update(from: UpdateVersion("0.1.10"), channel: .beta, host: .arm64)?.version
            == UpdateVersion("0.1.29"))
        #expect(appcast.update(from: UpdateVersion("0.1.20"), channel: .beta, host: .arm64)?.version
            == UpdateVersion("0.1.30"))
        #expect(appcast.update(from: UpdateVersion("0.1.19"), channel: .beta, host: .arm64)?.version
            == UpdateVersion("0.1.29"))
    }

    @Test func aStableClientIsNotOfferedABeta() throws {
        let appcast = UpdatesManifest.appcast(releases: [
            UpdatesManifest.release("0.1.30", channel: .beta),
            UpdatesManifest.release("0.1.29", channel: .stable),
        ])
        let offered = try #require(appcast.update(from: UpdateVersion("0.1.28"), channel: .stable, host: .arm64))
        #expect(offered.version == UpdateVersion("0.1.29"))
    }

    @Test func aBetaChannelClientSeesStableAndBetaAlike() throws {
        let appcast = UpdatesManifest.appcast(releases: [
            UpdatesManifest.release("0.1.30", channel: .stable),
            UpdatesManifest.release("0.1.29", channel: .beta),
        ])
        // Pre-1.0 the project publishes every build as a beta, so the beta channel is the default.
        let offered = try #require(appcast.update(from: UpdateVersion("0.1.28"), channel: .beta, host: .arm64))
        #expect(offered.version == UpdateVersion("0.1.30"))
        // The beta here is 0.1.29; a stable-preference client skips it and still takes the newer
        // stable 0.1.30, which is the whole point of ordering before filtering.
        #expect(appcast.update(from: UpdateVersion("0.1.28"), channel: .stable, host: .arm64)?.version
            == UpdateVersion("0.1.30"))
        #expect(UpdateChannel.isVisible(.stable, to: .stable))
        #expect(!UpdateChannel.isVisible(.beta, to: .stable))
        #expect(UpdateChannel.isVisible(.stable, to: .beta))
        #expect(UpdateChannel.isVisible(.beta, to: .beta))
    }

    @Test func aSkippedVersionIsNotOfferedAgain() throws {
        let onlyTheNewest = UpdatesManifest.appcast(releases: [UpdatesManifest.release("0.1.30")])
        #expect(onlyTheNewest.update(from: UpdateVersion("0.1.28"), channel: .beta, host: .arm64,
                                     skipping: UpdateVersion("0.1.30")) == nil)
        // Declining silences everything at or below what was declined. Offering 0.1.29 immediately
        // after someone said no to 0.1.30 would read as the app ignoring them.
        let both = UpdatesManifest.appcast(releases: [
            UpdatesManifest.release("0.1.30"),
            UpdatesManifest.release("0.1.29"),
        ])
        #expect(both.update(from: UpdateVersion("0.1.28"), channel: .beta, host: .arm64,
                            skipping: UpdateVersion("0.1.30")) == nil)
        // Skipping something older than what is on offer changes nothing.
        #expect(both.update(from: UpdateVersion("0.1.28"), channel: .beta, host: .arm64,
                            skipping: UpdateVersion("0.1.25"))?.version == UpdateVersion("0.1.30"))
        // And a newer release than the one declined breaks the silence.
        let newer = UpdatesManifest.appcast(releases: [
            UpdatesManifest.release("0.1.31"),
            UpdatesManifest.release("0.1.30"),
        ])
        #expect(newer.update(from: UpdateVersion("0.1.28"), channel: .beta, host: .arm64,
                             skipping: UpdateVersion("0.1.30"))?.version == UpdateVersion("0.1.31"))
    }

    @Test func aReleaseWithNoBuildForThisMacIsSkippedEntirely() throws {
        let armOnly = UpdatesManifest.appcast(releases: [
            UpdatesManifest.release("0.1.30", builds: [UpdatesManifest.build(.arm64)]),
            UpdatesManifest.release("0.1.29", builds: [UpdatesManifest.build(.x86_64), UpdatesManifest.build(.arm64)]),
        ])
        let offered = try #require(armOnly.update(from: UpdateVersion("0.1.28"), channel: .beta, host: .x86_64))
        #expect(offered.version == UpdateVersion("0.1.29"))
        #expect(armOnly.update(from: UpdateVersion("0.1.28"), channel: .beta, host: .universal) == nil)
    }

    @Test func aReleaseWithNoBuildsAtAllIsSkipped() throws {
        let appcast = UpdatesManifest.appcast(releases: [
            UpdatesManifest.release("0.1.30", builds: []),
            UpdatesManifest.release("0.1.29"),
        ])
        #expect(appcast.update(from: UpdateVersion("0.1.28"), channel: .beta, host: .arm64)?.version
            == UpdateVersion("0.1.29"))
    }

    @Test func sortingIsNewestFirstWhateverOrderTheFileArrivedIn() {
        let appcast = UpdatesManifest.appcast(releases: [
            UpdatesManifest.release("0.1.9"),
            UpdatesManifest.release("0.1.30"),
            UpdatesManifest.release("0.1.28"),
            UpdatesManifest.release("0.1.100"),
        ])
        #expect(appcast.sortedReleases.map(\.version.description) == ["0.1.100", "0.1.30", "0.1.28", "0.1.9"])
    }
}

/// Loading a committed fixture out of the test bundle.
func updatesFixture(_ name: String) -> URL? {
    Bundle.module.url(forResource: name, withExtension: nil, subdirectory: "Fixtures/Updates")
}
