#!/usr/bin/env bash
# Populates the app icon set from the Shoal artwork.
#
#   scripts/make-icons.sh
#
# Source of truth is brand/icon-shoal.svg, generated by brand/icon-shoal.py. This script rasterises
# it into brand/Assets.xcassets/AppIcon.appiconset, which scripts/bundle.sh then compiles into the
# .app with actool. Only dependency is rsvg-convert (Homebrew); the app itself stays dependency-free.
#
# The catalog deliberately lives outside Sources/ so SwiftPM does not ship a second, dead copy of it
# inside the resource bundle.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SVG="$ROOT/brand/icon-shoal.svg"
ICONSET="$ROOT/brand/Assets.xcassets/AppIcon.appiconset"

command -v rsvg-convert >/dev/null || { echo "error: rsvg-convert not found (brew install librsvg)" >&2; exit 1; }
[ -f "$SVG" ] || { echo "error: $SVG missing; run brand/icon-shoal.py" >&2; exit 1; }

mkdir -p "$ICONSET"

# slot name : point size : scale. actool wants mac idioms at these ten sizes.
SLOTS=(
  "icon_16x16:16:1" "icon_16x16@2x:16:2"
  "icon_32x32:32:1" "icon_32x32@2x:32:2"
  "icon_128x128:128:1" "icon_128x128@2x:128:2"
  "icon_256x256:256:1" "icon_256x256@2x:256:2"
  "icon_512x512:512:1" "icon_512x512@2x:512:2"
)

entries=()
for slot in "${SLOTS[@]}"; do
  IFS=: read -r name points scale <<<"$slot"
  pixels=$((points * scale))
  rsvg-convert -w "$pixels" -h "$pixels" "$SVG" -o "$ICONSET/$name.png"
  entries+=("    {\"idiom\" : \"mac\", \"size\" : \"${points}x${points}\", \"scale\" : \"${scale}x\", \"filename\" : \"$name.png\" }")
  echo "wrote $name.png (${pixels}px)"
done

cat > "$ICONSET/Contents.json" <<JSON
{
  "images" : [
$(IFS=$',\n'; echo "${entries[*]}")
  ],
  "info" : { "author" : "icon-shoal.py via scripts/make-icons.sh", "version" : 1 }
}
JSON

echo "wrote $ICONSET/Contents.json"